baseURL = "https://nevikw39.cf"
title = "nevikw39 | 如詩的▢律"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © {year} nevikw39. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
disqusShortname = "nevikw39"

# Google analytics
googleAnalytics = "UA-144209773-2"

enableRobotsTXT = true

enableEmoji = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
