baseURL = "/"
title = "nevikw39 ∥ 如詩的韻律"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © {year} nevikw39. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
disqusShortname = "nevikw39"

# Google analytics
googleAnalytics = "UA-144209773-2"

enableRobotsTXT = true

enableEmoji = true

hasCJKLanguage = true

enableGitInfo = true

summaryLength = 45

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  preserveTaxonomyNames = true
