mainSections = ["posts", "ramen", "programming"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

description = "各位好，我是來自清大資工的 nevikw39 牜攵犬羊，歡迎來到「如詩的韻律」！！"
images = ["images/nevikw39.jpg"]

logo = "images/nevikw39.png" # Logo image. Default to "images/logo.webp".
brand = "nevikw39 ∥ 如詩的韻律"
# menusPosition = "left" # Menus position: right(default), left or center.

palette = "teal" # Default palette. Optional.
palettes = [] # Available palettes. Default to ALL.

# fullWidth = true # Full width.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

math = true # Enable math globally.
# toc = false # Disable TOC globally.
# breadcrumb = false # Disable breadcrumb

# poweredBy = false # Whether to show powered by.

# featuredPostCount = 10 # The number of featured posts shown in sidebar.
# recentPostCount = 10 # The number of recent posts shown in sidebar.
# relatedPostCount = 10 # The number of related posts.
# categoryCount = 10 # The number of categories shown in sidebar.
# tagCount = 10 # The number of tags shown in sidebar.
# seriesCount = 10 # The number of series shown in sidebar.

# Custom CSS and JS
customCSS = []
customJS = []

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.
# tocSticky = true # Whether to make TOC stick to top when scrolling. Default to true.

color = "dark"

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

# Site verification
[siteVerification]
  google = "5cU5Gia3e5HCVOVKPF6LNPL47tsG4_CxU81oidPQaZc"
  bing = "49648A9FBF95D78C82C0517377262FFA"

[creativeCommons]
  # by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

[share]
  # addThis = "" # AddThis pubid.

# [fontSize]
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.2rem"
